name: Update k6 Version

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Update k6 version
          run: make update-version

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v7
          with:
            title: Update k6 version
            signoff: true
            commit-message: Update k6 version
            reviewers: dgzlopes